### PR TITLE
Revamp index.html homepage with Bootstrap 4

### PR DESCRIPTION
**Pull request by sunshinehombre**
Fixed the static issue I discussed with you earlier after reading through the Django tutorials. I do still get an `OperationalError at /bogging/: unable to open database file` (`sqlite3.OperationalError: unable to open database file`) with the traceback below. However, I think this might be because I'm running the server locally? Anyways, I'll let you take a look at it to see if I did anything wrong.
```
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/bogging/?ticker=TSLA

Django Version: 2.1.15
Python Version: 3.7.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'blog.apps.BlogConfig',
 'polls.apps.PollsConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "C:\Users\Jeffry\Projects\bogged-again-env\lib\site-packages\django\core\handlers\exception.py" in inner
  34.             response = get_response(request)

File "C:\Users\Jeffry\Projects\bogged-again-env\lib\site-packages\django\core\handlers\base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\Jeffry\Projects\bogged-again-env\lib\site-packages\django\core\handlers\base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\Jeffry\Projects\bogged-again-github\polls\views.py" in bogging
  20.         requested = boggedagain.newscrape(requested, ticker)

File "C:\Users\Jeffry\Projects\bogged-again-github\polls\boggedagain\boggedagain.py" in newscrape
  174.     connection = sqlite3.connect(f"{lpath}results.db")

Exception Type: OperationalError at /bogging/
Exception Value: unable to open database file
```

### CODE REVIEW

**Comment by sunshinehombre** [comment]
More info from the same error above.

Settings:
```
Setting | Value

ABSOLUTE_URL_OVERRIDES | {}
ADMINS | []
ALLOWED_HOSTS | ['0.0.0.0',  '127.0.0.1',  '34.216.183.71',  'boggedaga.in',  'www.boggedaga.in',  '52.42.94.130']
APPEND_SLASH | True
AUTHENTICATION_BACKENDS | ['django.contrib.auth.backends.ModelBackend']
AUTH_PASSWORD_VALIDATORS | '********************'
AUTH_USER_MODEL | 'auth.User'
BASE_DIR | 'C:\\Users\\Jeffry\\Projects\\bogged-again-github'
CACHES | {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS | 'default'
CACHE_MIDDLEWARE_KEY_PREFIX | '********************'
CACHE_MIDDLEWARE_SECONDS | 600
CSRF_COOKIE_AGE | 31449600
CSRF_COOKIE_DOMAIN | None
CSRF_COOKIE_HTTPONLY | False
CSRF_COOKIE_NAME | 'csrftoken'
CSRF_COOKIE_PATH | '/'
CSRF_COOKIE_SAMESITE | 'Lax'
CSRF_COOKIE_SECURE | False
CSRF_FAILURE_VIEW | 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME | 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS | []
CSRF_USE_SESSIONS | False
DATABASES | {'default': {'ATOMIC_REQUESTS': False,              'AUTOCOMMIT': True,              'CONN_MAX_AGE': 0,              'ENGINE': 'django.db.backends.sqlite3',              'HOST': '',              'NAME': 'C:\\Users\\Jeffry\\Projects\\bogged-again-github\\db.sqlite3',              'OPTIONS': {},              'PASSWORD': '********************',              'PORT': '',              'TEST': {'CHARSET': None,                       'COLLATION': None,                       'MIRROR': None,                       'NAME': None},              'TIME_ZONE': None,              'USER': ''}}
DATABASE_ROUTERS | []
DATA_UPLOAD_MAX_MEMORY_SIZE | 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS | 1000
DATETIME_FORMAT | 'N j, Y, P'
DATETIME_INPUT_FORMATS | ['%Y-%m-%d %H:%M:%S',  '%Y-%m-%d %H:%M:%S.%f',  '%Y-%m-%d %H:%M',  '%Y-%m-%d',  '%m/%d/%Y %H:%M:%S',  '%m/%d/%Y %H:%M:%S.%f',  '%m/%d/%Y %H:%M',  '%m/%d/%Y',  '%m/%d/%y %H:%M:%S',  '%m/%d/%y %H:%M:%S.%f',  '%m/%d/%y %H:%M',  '%m/%d/%y']
DATE_FORMAT | 'N j, Y'
DATE_INPUT_FORMATS | ['%Y-%m-%d',  '%m/%d/%Y',  '%m/%d/%y',  '%b %d %Y',  '%b %d, %Y',  '%d %b %Y',  '%d %b, %Y',  '%B %d %Y',  '%B %d, %Y',  '%d %B %Y',  '%d %B, %Y']
DEBUG | True
DEBUG_PROPAGATE_EXCEPTIONS | False
DECIMAL_SEPARATOR | '.'
DEFAULT_CHARSET | 'utf-8'
DEFAULT_CONTENT_TYPE | 'text/html'
DEFAULT_EXCEPTION_REPORTER_FILTER | 'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE | 'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL | 'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE | ''
DEFAULT_TABLESPACE | ''
DISALLOWED_USER_AGENTS | []
EMAIL_BACKEND | 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST | 'localhost'
EMAIL_HOST_PASSWORD | '********************'
EMAIL_HOST_USER | ''
EMAIL_PORT | 25
EMAIL_SSL_CERTFILE | None
EMAIL_SSL_KEYFILE | '********************'
EMAIL_SUBJECT_PREFIX | '[Django] '
EMAIL_TIMEOUT | None
EMAIL_USE_LOCALTIME | False
EMAIL_USE_SSL | False
EMAIL_USE_TLS | False
FILE_CHARSET | 'utf-8'
FILE_UPLOAD_DIRECTORY_PERMISSIONS | None
FILE_UPLOAD_HANDLERS | ['django.core.files.uploadhandler.MemoryFileUploadHandler',  'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE | 2621440
FILE_UPLOAD_PERMISSIONS | None
FILE_UPLOAD_TEMP_DIR | None
FIRST_DAY_OF_WEEK | 0
FIXTURE_DIRS | []
FORCE_SCRIPT_NAME | None
FORMAT_MODULE_PATH | None
FORM_RENDERER | 'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS | []
INSTALLED_APPS | ['django.contrib.admin',  'django.contrib.auth',  'django.contrib.contenttypes',  'django.contrib.sessions',  'django.contrib.messages',  'django.contrib.staticfiles',  'blog.apps.BlogConfig',  'polls.apps.PollsConfig']
INTERNAL_IPS | []
LANGUAGES | [('af', 'Afrikaans'),  ('ar', 'Arabic'),  ('ast', 'Asturian'),  ('az', 'Azerbaijani'),  ('bg', 'Bulgarian'),  ('be', 'Belarusian'),  ('bn', 'Bengali'),  ('br', 'Breton'),  ('bs', 'Bosnian'),  ('ca', 'Catalan'),  ('cs', 'Czech'),  ('cy', 'Welsh'),  ('da', 'Danish'),  ('de', 'German'),  ('dsb', 'Lower Sorbian'),  ('el', 'Greek'),  ('en', 'English'),  ('en-au', 'Australian English'),  ('en-gb', 'British English'),  ('eo', 'Esperanto'),  ('es', 'Spanish'),  ('es-ar', 'Argentinian Spanish'),  ('es-co', 'Colombian Spanish'),  ('es-mx', 'Mexican Spanish'),  ('es-ni', 'Nicaraguan Spanish'),  ('es-ve', 'Venezuelan Spanish'),  ('et', 'Estonian'),  ('eu', 'Basque'),  ('fa', 'Persian'),  ('fi', 'Finnish'),  ('fr', 'French'),  ('fy', 'Frisian'),  ('ga', 'Irish'),  ('gd', 'Scottish Gaelic'),  ('gl', 'Galician'),  ('he', 'Hebrew'),  ('hi', 'Hindi'),  ('hr', 'Croatian'),  ('hsb', 'Upper Sorbian'),  ('hu', 'Hungarian'),  ('ia', 'Interlingua'),  ('id', 'Indonesian'),  ('io', 'Ido'),  ('is', 'Icelandic'),  ('it', 'Italian'),  ('ja', 'Japanese'),  ('ka', 'Georgian'),  ('kab', 'Kabyle'),  ('kk', 'Kazakh'),  ('km', 'Khmer'),  ('kn', 'Kannada'),  ('ko', 'Korean'),  ('lb', 'Luxembourgish'),  ('lt', 'Lithuanian'),  ('lv', 'Latvian'),  ('mk', 'Macedonian'),  ('ml', 'Malayalam'),  ('mn', 'Mongolian'),  ('mr', 'Marathi'),  ('my', 'Burmese'),  ('nb', 'Norwegian Bokmål'),  ('ne', 'Nepali'),  ('nl', 'Dutch'),  ('nn', 'Norwegian Nynorsk'),  ('os', 'Ossetic'),  ('pa', 'Punjabi'),  ('pl', 'Polish'),  ('pt', 'Portuguese'),  ('pt-br', 'Brazilian Portuguese'),  ('ro', 'Romanian'),  ('ru', 'Russian'),  ('sk', 'Slovak'),  ('sl', 'Slovenian'),  ('sq', 'Albanian'),  ('sr', 'Serbian'),  ('sr-latn', 'Serbian Latin'),  ('sv', 'Swedish'),  ('sw', 'Swahili'),  ('ta', 'Tamil'),  ('te', 'Telugu'),  ('th', 'Thai'),  ('tr', 'Turkish'),  ('tt', 'Tatar'),  ('udm', 'Udmurt'),  ('uk', 'Ukrainian'),  ('ur', 'Urdu'),  ('vi', 'Vietnamese'),  ('zh-hans', 'Simplified Chinese'),  ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI | ['he', 'ar', 'fa', 'ur']
LANGUAGE_CODE | 'en-us'
LANGUAGE_COOKIE_AGE | None
LANGUAGE_COOKIE_DOMAIN | None
LANGUAGE_COOKIE_NAME | 'django_language'
LANGUAGE_COOKIE_PATH | '/'
LOCALE_PATHS | []
LOGGING | {}
LOGGING_CONFIG | 'logging.config.dictConfig'
LOGIN_REDIRECT_URL | '/accounts/profile/'
LOGIN_URL | '/accounts/login/'
LOGOUT_REDIRECT_URL | None
MANAGERS | []
MEDIA_ROOT | 'C:\\Users\\Jeffry\\Projects\\bogged-again-github\\media'
MEDIA_URL | '/pics/'
MESSAGE_STORAGE | 'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE | ['django.middleware.security.SecurityMiddleware',  'django.contrib.sessions.middleware.SessionMiddleware',  'django.middleware.common.CommonMiddleware',  'django.middleware.csrf.CsrfViewMiddleware',  'django.contrib.auth.middleware.AuthenticationMiddleware',  'django.contrib.messages.middleware.MessageMiddleware',  'django.middleware.clickjacking.XFrameOptionsMiddleware']
MIGRATION_MODULES | {}
MONTH_DAY_FORMAT | 'F j'
NUMBER_GROUPING | 0
PASSWORD_HASHERS | '********************'
PASSWORD_RESET_TIMEOUT_DAYS | '********************'
PREPEND_WWW | False
ROOT_URLCONF | 'ebdjango.urls'
SECRET_KEY | '********************'
SECURE_BROWSER_XSS_FILTER | False
SECURE_CONTENT_TYPE_NOSNIFF | False
SECURE_HSTS_INCLUDE_SUBDOMAINS | False
SECURE_HSTS_PRELOAD | False
SECURE_HSTS_SECONDS | 0
SECURE_PROXY_SSL_HEADER | None
SECURE_REDIRECT_EXEMPT | []
SECURE_SSL_HOST | None
SECURE_SSL_REDIRECT | False
SERVER_EMAIL | 'root@localhost'
SESSION_CACHE_ALIAS | 'default'
SESSION_COOKIE_AGE | 1209600
SESSION_COOKIE_DOMAIN | None
SESSION_COOKIE_HTTPONLY | True
SESSION_COOKIE_NAME | 'sessionid'
SESSION_COOKIE_PATH | '/'
SESSION_COOKIE_SAMESITE | 'Lax'
SESSION_COOKIE_SECURE | False
SESSION_ENGINE | 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE | False
SESSION_FILE_PATH | None
SESSION_SAVE_EVERY_REQUEST | False
SESSION_SERIALIZER | 'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE | 'ebdjango.settings'
SHORT_DATETIME_FORMAT | 'm/d/Y P'
SHORT_DATE_FORMAT | 'm/d/Y'
SIGNING_BACKEND | 'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS | []
STATICFILES_DIRS | []
STATICFILES_FINDERS | ['django.contrib.staticfiles.finders.FileSystemFinder',  'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE | 'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT | None
STATIC_URL | '/static/'
TEMPLATES | [{'APP_DIRS': True,   'BACKEND': 'django.template.backends.django.DjangoTemplates',   'DIRS': [],   'OPTIONS': {'context_processors': ['django.template.context_processors.debug',                                      'django.template.context_processors.request',                                      'django.contrib.auth.context_processors.auth',                                      'django.contrib.messages.context_processors.messages']}}]
TEST_NON_SERIALIZED_APPS | []
TEST_RUNNER | 'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR | ','
TIME_FORMAT | 'P'
TIME_INPUT_FORMATS | ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE | 'EST'
USE_I18N | True
USE_L10N | True
USE_THOUSAND_SEPARATOR | False
USE_TZ | True
USE_X_FORWARDED_HOST | False
USE_X_FORWARDED_PORT | False
WSGI_APPLICATION | 'ebdjango.wsgi.application'
X_FRAME_OPTIONS | 'SAMEORIGIN'
YEAR_MONTH_FORMAT | 'F Y'


```

**Comment by deekew33** [comment]
So Django looks at the paths differently when hosted on the AWS server vs when hosted locally(or maybe it's just something to do with Apache). Either way, on the EC2 instance it seems to need a full path, while on a local server I think it just needs a relative path. On line 24 of boggedagain.py I specified a local path in the case we're not on the EC2 instance, but I think that might not be necessary - setting lpath(I probably should've named it linuxpath to be more clear) equal to an empty string still allows it to work locally, at least on my end. You can try that and see if it works, and remove it if it does.

**Comment by sunshinehombre** [comment]
Hmm so I commented out the `if not os.path.exists(...) else ...` and replaced it with `lpath = ''`. I got the following error instead. I'll look into it more but if it works for you then that's good.
```
ValueError at /bogging/
signal only works in main thread

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/bogging/?ticker=VIE

Django Version: 2.1.15
Python Version: 3.7.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'blog.apps.BlogConfig',
 'polls.apps.PollsConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "C:\Users\Jeffry\Projects\bogged-again-env\lib\site-packages\django\core\handlers\exception.py" in inner
  34.             response = get_response(request)

File "C:\Users\Jeffry\Projects\bogged-again-env\lib\site-packages\django\core\handlers\base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\Jeffry\Projects\bogged-again-env\lib\site-packages\django\core\handlers\base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\Jeffry\Projects\bogged-again-github\polls\views.py" in bogging
  20.         requested = boggedagain.newscrape(requested, ticker)

File "C:\Users\Jeffry\Projects\bogged-again-github\polls\boggedagain\boggedagain.py" in newscrape
  261.         run_spider(ZacksSpider, stuff)

File "C:\Users\Jeffry\Projects\bogged-again-github\polls\boggedagain\boggedagain.py" in run_spider
  239.             'USER_AGENT': 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)'

File "C:\Users\Jeffry\Projects\bogged-again-env\lib\site-packages\scrapy\crawler.py" in __init__
  268.         install_shutdown_handlers(self._signal_shutdown)

File "C:\Users\Jeffry\Projects\bogged-again-env\lib\site-packages\scrapy\utils\ossignal.py" in install_shutdown_handlers
  22.     reactor._handleSignals()

File "C:\Users\Jeffry\Projects\bogged-again-env\lib\site-packages\twisted\internet\posixbase.py" in _handleSignals
  295.         _SignalReactorMixin._handleSignals(self)

File "C:\Users\Jeffry\Projects\bogged-again-env\lib\site-packages\twisted\internet\base.py" in _handleSignals
  1243.             signal.signal(signal.SIGINT, self.sigInt)

File "C:\Users\Jeffry\Anaconda3\lib\signal.py" in signal
  47.     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))

Exception Type: ValueError at /bogging/
Exception Value: signal only works in main thread
```

**Comment by deekew33** [comment]
That error usually appears as a result of the Twisted reactor doing something- Scrapy works on the Twisted reactor, and the reactor has the property of not being restartable within the main thread. There is only one global reactor too, and I don't quite know the details. I'll back up my current local copy(since I messed around with boggedagain.py), merge your request into the git, and I'll test your stuff locally.

**Pull request merged**
